### ISSUE TITLE
Getting an error 

### ISSUE THREAD

**Issue by 98reesereese89** [BeChris100/osintgram4j#2]
./bin/osintgram4j
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/adolla/Downloads/osintgram4j/build/pkg/osintgram4j/lib/app/libosintgram4j-cxx.so: /home/adolla/Downloads/osintgram4j/build/pkg/osintgram4j/lib/app/libosintgram4j-cxx.so: undefined symbol: _ZTVSt9basic_iosIcSt11char_traitsIcEE
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2451)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2063)
	at net.bc100dev.osintgram4j.NativeLoader.load(NativeLoader.java:44)
	at net.bc100dev.osintgram4j.MainClass.main(MainClass.java:87)

**Comment by BeChris100** [comment]
Found the specific culprit on where the error was, which in this case, it was the Building Script. It used a different flag for the CXX Module Build, which caused the error to happen. For now, this should be fixed.

If not, then keep me up to date. I have E-Mail Notifications enabled, in case of issues like these.
