### ISSUE TITLE
Error when running executable

### ISSUE THREAD

**Issue by MightyRavenDark88** [BeChris100/osintgram4j#7]
I get this right after executing bin/osintgram4j:

While running the Application, the Main Thread crashed.
For some reason, a piece of code was not surrounded within a try-catch, or a Runtime Error was encountered.

Error/Exception Stacktrace:
net.bc100dev.commons.ApplicationRuntimeException: java.io.FileNotFoundException: AppSettings.cfg (No such file or directory)
	at net.bc100dev.osintgram4j.Settings.loadSettings(Settings.java:59)
	at net.bc100dev.osintgram4j.MainClass.main(MainClass.java:109)
Caused by: java.io.FileNotFoundException: AppSettings.cfg (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at net.bc100dev.osintgram4j.Settings.loadSettings(Settings.java:55)
	... 1 more

**Comment by BeChris100** [comment]
I know, what the issue actually is.

You changed the working directory, which makes Osintgram4j expect that the Settings file is also there, but by changing the directory with `cd`, that file becomes inaccessible.

I'll be working on a fix, so that it uses an absolute file path to it.

**Comment by BeChris100** [comment]
I hope that the updated code fixed the issue for you. If not, please respond within this issue, so that I'll look deeper into it.

**Comment by MightyRavenDark88** [comment]
seems to work now but I'm not sure how to use the executable

**Comment by BeChris100** [comment]
Basically, after you run `build.sh` and no errors pop up, the executable should be located under `out/pkg/osintgram4j/bin/osintgram4j`, which is the file that you should be able to run.

However, if you are referring on how to use this project, then I'd suggest on waiting, since it is still under development. However, either this or next month, I should be finished with the Stage 1 (see `Progress.md` file that I recently added).
